---
title: "Instacart Visualization"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---
  
```{r setup, include=FALSE}

# Load libraries

library(flexdashboard)
library(tidyverse)
library(janitor)
library(stringr)
library(forcats)
library(viridis)
library(plotly)
library(magrittr)
library(readr)
library(scales)

```


```{r data_tidy}

# Load the data and clean names

instacart = read_csv("./data/instacart_train_data.csv.zip") %>%
  clean_names() %>%
  distinct()


```


Column {data-width=500}
-----------------------------------------------------------------------

### Department Frequency

```{r department_frequency}

barplot_department_ggplot = instacart %>% 
  count(department) %>% # count the number of items sold in each department
  mutate(department = fct_reorder(department, n)) %>% # reorder department by n
  ggplot(aes(x = department, y = n, fill = department)) + # barplot of no.items sold by dept.
    geom_bar(stat = "identity") + 
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 
    scale_y_continuous(name = "N", labels = scales::unit_format("k", 1e-3)) 

ggplotly(barplot_department_ggplot)

```

Column {.tabset data-width=500}
-----------------------------------------------------------------------

### Most Popular Products by Aisle in the Produce Department

```{r popular_products}

barplot_popular_produce = instacart %>% 
  filter(department == "produce") %>% # only keep observations of items in produce dept.
  group_by(aisle) %>% # group by aisle in produce dept.
  count(product_name) %>% # count no. product sold
  top_n(2) %>% # keep the top 2 most sold products in each aisle
  ggplot(aes(x = aisle, y = n, fill = product_name)) +
        geom_bar(stat = "identity", position = "dodge") +
        theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
        labs(title = "Most Popular Products by Aisle in Produce Department") + 
        guides(fill = FALSE)

ggplotly(barplot_popular_produce) %>% layout(showlegend = FALSE)

```

### Distribution of Order Hour of Day by Department

```{r boxplot_order_hour}

# distribution of what time of day items were sold by dept. 

boxplot_order_hour = instacart %>% 
  ggplot(aes(x = department, y = order_hour_of_day, fill = department)) + 
        geom_boxplot() +
        theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
        labs(title = "Order Hour of Day by Department")

ggplotly(boxplot_order_hour)

```

